---

    # The name space should be that of the current resource, or that of the component
    # nginx_apigw_namespace is set when a component update is triggered from a Deployment
    - name: Set the nginx_apigw Namespace
      set_fact:
        nginx_apigw_namespace: "{{ nginx_apigw_namespace | default( ansible_operator_meta.namespace ) }}"

    - name: Create Controller facts
      set_fact:
        nginx_controller_user_email: "{{ spec.user_email }}"
        nginx_controller_fqdn: "{{ spec.fqdn }}"
        nginx_controller_validate_certs: "{{ spec.validate_certs }}"

    - name: Set the controller Auth cache file
      set_fact:
        token_cache: "{{ '/var/tmp/auth-cache_' ~ nginx_apigw_namespace ~ '_' ~ ansible_operator_meta.name ~ '_' ~ spec.secret ~ '.auth' }}"

    - name: Stat the controller Auth cache
      stat:
        path: "{{ token_cache }}"
      register: token_stat

    - name: Get the time
      shell: "date +%s"
      register: date

    - name: Login and Refresh the Auth Token
      block:

      - name: Ensure the auth token directory exists
        file:
          path: "{{ '/tmp/ctl-' ~ nginx_apigw_namespace }}"
          mode: "0700"
          state: directory

      - name: Get the Secret password
        k8s_info:
          kind: Secret
          name: "{{ spec.secret }}"
          namespace: "{{ nginx_apigw_namespace }}"
        register: ctl_creds

      - name: Add Controller user_password fact
        set_fact:
          nginx_controller_user_password: "{{ ctl_creds.resources.0.data.user_password | b64decode }}"

      - name: Retrieve the NGINX Controller auth token
        include_role:
          name: nginxinc.nginx_controller.nginx_controller_generate_token

      - name: Store the token in the cache
        copy:
          dest: "{{ token_cache }}"
          mode: "0600"
          content: "{{ nginx_controller_auth_token }}"

      when: ( token_stat.stat.exists == False ) or ( ( token_stat.stat.mtime |int) <= ( ( date.stdout |int) - 1800 ) )

    - name: Use Cached Auth Token
      set_fact:
        nginx_controller_auth_token: "{{ lookup('file', token_cache) }}"
      when: ( token_stat.stat.exists ) and ( ( token_stat.stat.mtime |int) > ( ( date.stdout |int) - 1800 ) )

...

