---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.apigw.nginx.com
spec:
  group: apigw.nginx.com
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Gateway is the Schema for the gateways API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Gateway
            type: object
            properties:
              user_email:
                description: "The email address used to login to the controller"
                type: string
              secret:
                description: "The secret which stores the password used to login to the controller"
                type: string
              fqdn:
                description: "The FQDN or IP address of the controller"
                type: string
              validate_certs:
                description: "Should we validate the certificate chain of the Controller API"
                type: boolean
                default: false
              instance_group:
                description: "The Instance Group tag 'ig:<tag>' on the gateways we're registering with"
                type: string
              instance_location:
                description: "The infrastructure location that the pods will join"
                type: string
                default: "unspecified"
              deployment:
                description: Spec defines the desired deployment of NGINX pods
                type: object
                x-kubernetes-preserve-unknown-fields: true
            anyOf:
              - required:
                - user_email
                - fqdn
                - secret
                - instance_group
                - deployment
          status:
            description: Status defines the observed state of Gateway
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
